//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookInventory
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [Display(Name = "ISBN")]
        [Required(ErrorMessage = "ISBN required")]
        public int ISBN_Code { get; set; }
        [Display(Name = "Book Title")]
        [Required(ErrorMessage = "Book Title required")]
        public string Book_Title { get; set; }
        [Display(Name = "Author")]
        [Required(ErrorMessage = "Author required")]
        public string Author { get; set; }
        [Display(Name = "Publication")]
        [Required(ErrorMessage = "Publication required")]
        public string Publication { get; set; }
        [Display(Name = "Publication Year")]
        [Required(ErrorMessage = "Publication year required")]

        public Nullable<int> Publication_year { get; set; }
    }
}
