//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookInventory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class inventoryDBEntities : DbContext
    {
        public inventoryDBEntities()
            : base("name=inventoryDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
    
        public virtual int st_insertBook(Nullable<int> iSBN_Code, string title, string author, string publication, Nullable<int> publication_year)
        {
            var iSBN_CodeParameter = iSBN_Code.HasValue ?
                new ObjectParameter("ISBN_Code", iSBN_Code) :
                new ObjectParameter("ISBN_Code", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var publicationParameter = publication != null ?
                new ObjectParameter("publication", publication) :
                new ObjectParameter("publication", typeof(string));
    
            var publication_yearParameter = publication_year.HasValue ?
                new ObjectParameter("publication_year", publication_year) :
                new ObjectParameter("publication_year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_insertBook", iSBN_CodeParameter, titleParameter, authorParameter, publicationParameter, publication_yearParameter);
        }
    
        public virtual int st_insertBook1(Nullable<int> iSBN_Code, string title, string author, string publication, Nullable<int> publication_year)
        {
            var iSBN_CodeParameter = iSBN_Code.HasValue ?
                new ObjectParameter("ISBN_Code", iSBN_Code) :
                new ObjectParameter("ISBN_Code", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var authorParameter = author != null ?
                new ObjectParameter("author", author) :
                new ObjectParameter("author", typeof(string));
    
            var publicationParameter = publication != null ?
                new ObjectParameter("publication", publication) :
                new ObjectParameter("publication", typeof(string));
    
            var publication_yearParameter = publication_year.HasValue ?
                new ObjectParameter("publication_year", publication_year) :
                new ObjectParameter("publication_year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("st_insertBook1", iSBN_CodeParameter, titleParameter, authorParameter, publicationParameter, publication_yearParameter);
        }
    }
}
